import time
import os

print('请为您的AI女朋友命名!')
AI_name = input()
os.system('cls')
print('请您与AI女友对话：')
text = input()
os.system('cls')
print('您：')
print(text)
time.sleep(3)
os.system('cls')
print('您的AI女友正在回复，清稍等……')
time.sleep(3)
os.system('cls')
print((AI_name+':'))
print('抱歉，因为您刚才说的话，我认为我们不合适，分手吧')
os.system('pause')
os.system('cls')
print('你被甩了！')
os.system('pause')